window.BLOCOS=[
{id:"d1-No",arquivo:"desafio1.py",nome:"No",tipo:"classe",
e:"Classe. É o molde de um nó da lista encadeada.",
s:"Cada elemento da pilha é um No. Sem ele não existe a 'corrente' que forma a pilha.",
f:"Guarda um valor e uma referência para o nó que está logo abaixo dele.",
c:"O __init__ recebe valor e proximo (padrão None). None marca o nó da base, o fim da corrente.",
r:"valor: o dado (número no desafio 1, operador ou parêntese no desafio 2). proximo: o nó de baixo, opcional.",
p:"Um objeto No com os atributos valor e proximo.",
u:[],ub:["d1-empilhar"],
a:"A importação não falha, porque No só é usado dentro de empilhar. O erro (NameError) aparece na primeira vez que algo é empilhado, ou seja, ao ler o primeiro número em avaliar. Na prática o programa fica inutilizável.",
i:"empilhar e, por consequência, avaliar, converter e main.py.",
n:[["self.valor = valor","Guarda o dado do nó."],["self.proximo = proximo","Liga este nó ao de baixo. É isso que forma a pilha."]]},
{id:"d1-Pilha",arquivo:"desafio1.py",nome:"Pilha (classe e __init__)",tipo:"classe + construtor",
e:"Classe com seu construtor. Os métodos aparecem como blocos separados logo abaixo.",
s:"Implementa a pilha LIFO pedida no enunciado, de forma encadeada, sem usar list.",
f:"Ao criar Pilha(), ela nasce vazia: sem nó no topo e com contador 0.",
c:"topo_no aponta para o nó do topo (só ele é acessado diretamente). contador existe para tamanho() não precisar percorrer a corrente.",
r:"Só self.",p:"Uma pilha vazia.",
u:[],ub:["d1-avaliar","d2-converter"],
a:"Quebra tudo: desafio2.py faz 'from desafio1 import Pilha', então main.py falha com ImportError já ao iniciar.",
i:"desafio2.py inteiro, avaliar e main.py.",
n:[["self.topo_no = None","None significa pilha vazia."],["self.contador = 0","Tamanho mantido à parte (tamanho() fica O(1))."]]},
{id:"d1-empilhar",arquivo:"desafio1.py",nome:"empilhar",tipo:"método de Pilha",
e:"Método da classe Pilha.",s:"Colocar um valor no topo da pilha.",
f:"Cria um nó novo apontando para o topo atual, faz esse nó ser o novo topo e soma 1 ao contador.",
c:"Nenhum nó antigo é movido: o novo só 'se pendura' na frente. Por isso custa O(1).",
r:"novo_valor: o que guardar.",p:"Nada (None). Altera a pilha.",
u:["d1-No"],ub:["d1-avaliar","d2-converter"],
a:"AttributeError na primeira chamada. Todo o programa falha: avaliar empilha o primeiro número e converter empilha o primeiro operador ou parêntese.",
i:"avaliar, converter e main.py.",
n:[["self.topo_no = No(","O novo nó aponta para o topo antigo e vira o topo."],["self.contador += 1","Mantém o tamanho atualizado."]]},
{id:"d1-desempilhar",arquivo:"desafio1.py",nome:"desempilhar",tipo:"método de Pilha",
e:"Método da classe Pilha.",s:"Remover e devolver o elemento do topo.",
f:"Guarda o valor do topo, faz o nó de baixo virar o topo, diminui o contador e devolve o valor guardado.",
c:"Não verifica se a pilha está vazia: em pilha vazia daria erro (None.valor). Quem chama é responsável: avaliar confere tamanho() e converter confere vazia().",
r:"Só self.",p:"O valor removido. A pilha perde um elemento.",
u:[],ub:["d1-avaliar","d2-converter"],
a:"AttributeError assim que alguém tentar desempilhar: no primeiro operador em avaliar e no esvaziamento da pilha em converter. Nenhuma expressão com operador funciona.",
i:"avaliar, converter e main.py.",
n:[["valor_removido = self.topo_no.valor","Guarda o valor antes de o nó ser descartado."],["self.topo_no = self.topo_no.proximo","O nó de baixo vira o topo."]]},
{id:"d1-topo",arquivo:"desafio1.py",nome:"topo",tipo:"método de Pilha",
e:"Método da classe Pilha.",s:"Olhar o elemento do topo sem removê-lo.",
f:"Devolve o valor do nó do topo.",c:"Não altera a pilha. Também não verifica pilha vazia.",
r:"Só self.",p:"O valor do topo.",
u:[],ub:["d1-avaliar","d2-converter"],
a:"AttributeError em converter ao ver ')' ou um operador com a pilha não vazia, e em avaliar no return final. Nenhum resultado válido chega a ser produzido.",
i:"avaliar, converter e main.py."},
{id:"d1-vazia",arquivo:"desafio1.py",nome:"vazia",tipo:"método de Pilha",
e:"Método da classe Pilha.",s:"Informar se a pilha não tem elementos.",
f:"Devolve True quando topo_no é None.",c:"Uma única comparação.",r:"Só self.",p:"True ou False.",
u:[],ub:["d2-converter"],
a:"AttributeError em toda conversão: o laço final de converter ('while not operadores.vazia()') roda para qualquer expressão. avaliar não usa vazia, mas nunca é alcançado.",
i:"converter e, por consequência, main.py."},
{id:"d1-tamanho",arquivo:"desafio1.py",nome:"tamanho",tipo:"método de Pilha",
e:"Método da classe Pilha.",s:"Dizer quantos elementos há na pilha.",
f:"Devolve o contador, sem percorrer os nós.",c:"Por isso é O(1).",r:"Só self.",p:"Um inteiro.",
u:[],ub:["d1-avaliar"],
a:"AttributeError em avaliar: no primeiro operador (verificação '< 2') e no fim ('!= 1'). converter não usa tamanho, mas o resultado nunca é calculado.",
i:"avaliar e main.py (a etapa de cálculo)."},
{id:"d1-visualizar",arquivo:"desafio1.py",nome:"visualizar",tipo:"método de Pilha",
e:"Método extra da Pilha, acrescentado para o rastreamento.",
s:"O enunciado exige mostrar o conteúdo da pilha a cada passo sem destruí-la. Como a pilha é encadeada, é preciso percorrê-la.",
f:"Percorre os nós do topo até a base copiando os valores para uma lista e a inverte, deixando da base para o topo.",
c:"Usa a variável auxiliar atual, então topo_no nunca muda. Devolve uma cópia: mexer nela não afeta a pilha. Custa O(n).",
r:"Só self.",p:"Uma lista (base → topo).",
u:[],ub:["d1-avaliar","d2-converter"],
a:"AttributeError já no primeiro token processado, tanto em avaliar quanto em converter (ambos chamam visualizar para montar o trace).",
i:"avaliar, converter e toda a impressão do rastreamento em main.py.",
n:[["atual = self.topo_no","Auxiliar que percorre sem mexer no topo."],["itens.reverse()","Percorreu topo→base; inverte para base→topo."]]},
{id:"d1-fmt",arquivo:"desafio1.py",nome:"fmt",tipo:"função",
e:"Função de formatação.",s:"Padronizar a exibição de números (exigida pelo enunciado).",
f:"Usa o formato :g para mostrar 8 em vez de 8.0, mantendo 2.5.",c:"Só afeta a exibição. Os cálculos continuam em float.",
r:"v: um número.",p:"Uma string.",
u:[],ub:["m-imports","m-imp1","m-processar"],
a:"main.py falha com ImportError ao iniciar, pois importa fmt.",i:"main.py inteiro."},
{id:"d1-tokenizar",arquivo:"desafio1.py",nome:"tokenizar (pós-fixa)",tipo:"função",
e:"Função de separação em tokens.",s:"Transformar a pós-fixa em lista de tokens.",
f:"Chama split(), pois na pós-fixa os tokens já vêm separados por espaço.",
c:"Existe outra função tokenizar em desafio2.py, bem diferente. Por isso main.py importa esta como tokenizar_posfixa.",
r:"expressao: string pós-fixa.",p:"Lista de strings.",
u:[],ub:["m-imports","m-processar"],
a:"main.py falha com ImportError ao iniciar.",i:"main.py inteiro."},
{id:"d1-avaliar",arquivo:"desafio1.py",nome:"avaliar",tipo:"função",
e:"Função principal do Desafio 1.",s:"Calcular o valor de uma expressão pós-fixa usando uma pilha de números.",
f:"Para cada token: número é empilhado; operador desempilha dois números, calcula e empilha o resultado. No fim deve sobrar exatamente um número. Cada passo grava uma 'foto' da pilha no trace.",
c:"A pilha guarda operandos à espera de um operador. A ordem importa: b (direita) sai primeiro, depois a (esquerda), e calcula-se a op b. Erros viram mensagens devolvidas, sem exceção.",
r:"tokens: lista de strings (números e operadores + - * / ^).",
p:"Uma tripla (trace, resultado, erro). Em caso de erro, resultado é None e o trace vai até o ponto da falha.",
u:["d1-Pilha","d1-empilhar","d1-desempilhar","d1-tamanho","d1-visualizar","d1-topo"],ub:["m-processar"],
a:"main.py falha com ImportError ao iniciar. Se a importação existisse mas a função não, nada seria calculado.",
i:"processar e main.py (resultado e rastreamento do Desafio 1).",
n:[["if pilha.tamanho() < 2","Operador precisa de 2 operandos."],["b = pilha.desempilhar()","b sai primeiro: é o operando da direita."],["a = pilha.desempilhar()","a é o da esquerda. Em '5 2 -' vale 5 - 2."],["if b == 0:","Evita ZeroDivisionError."],["resultado = a ** b","Pode estourar ou dar erro, tratado no try."],["isinstance(resultado, complex)","Ex.: -8 ^ 0.5 daria complexo."],["pilha.empilhar(float(token))","Número entra na pilha como float."],["trace.append(","Foto da pilha após cada token."],["if pilha.tamanho() != 1","Sobrou operando: expressão malformada."]]},
{id:"d2-import",arquivo:"desafio2.py",nome:"import da Pilha",tipo:"import",
e:"Importação.",s:"Reaproveitar a Pilha do desafio 1 na conversão.",
f:"Traz a classe Pilha para este arquivo.",c:"É a única ligação de desafio2.py com desafio1.py.",
r:"—",p:"O nome Pilha disponível neste arquivo.",
u:["d1-Pilha"],ub:["d2-converter"],
a:"Importar não falha, mas converter dá NameError ao criar Pilha(), para qualquer expressão com caracteres válidos.",i:"converter e main.py."},
{id:"d2-const",arquivo:"desafio2.py",nome:"PRIORIDADE e DIREITA",tipo:"constantes",
e:"Duas tabelas de regras (dicionário e conjunto).",s:"Guardar as regras de precedência e associatividade como dados, sem cadeias de if.",
f:"PRIORIDADE dá o nível de cada operador (maior = mais forte). DIREITA lista os associativos à direita (só ^).",
c:"Para mudar uma regra basta mudar a tabela. Todo operador fora de DIREITA é associativo à esquerda.",
r:"—",p:"Dados consultados por converter.",
u:[],ub:["d2-converter"],
a:"Sem PRIORIDADE: NameError no primeiro token (converter a consulta para identificar operadores). Sem DIREITA: o erro só aparece ao chegar um operador com outro operador já na pilha, então '3 + 4' ainda funcionaria.",
i:"converter e main.py."},
{id:"d2-tokenizar",arquivo:"desafio2.py",nome:"tokenizar (notação usual)",tipo:"função",
e:"Função de separação em tokens (leitura caractere a caractere).",
s:"A entrada pode vir sem espaços ('3+42*(7-1)'); split() não resolveria.",
f:"Percorre a string: ignora espaços, junta dígitos e pontos em um único número (42, 12.5), e trata cada operador ou parêntese como token próprio. Outros caracteres geram erro.",
c:"inicio é a posição lida; fim avança enquanto o caractere ainda é parte do número. O trecho recortado é validado com float, o que recusa '1.2.3' e '.'. Não usa pilha.",
r:"expressao: string na notação usual.",p:"Tupla (tokens, erro): lista de tokens, ou (None, mensagem).",
u:[],ub:["d2-converter"],
a:"converter dá NameError ao chamar tokenizar, para qualquer expressão. main.py continua carregando, mas a conversão não roda.",
i:"converter e main.py.",
n:[["elif caractere.isdigit()","Começo de um número."],["while fim < tamanho","Estende o número enquanto houver dígito ou ponto."],["float(numero)","Valida o número recortado."],["elif caractere in","Operador ou parêntese: um token cada."]]},
{id:"d2-converter",arquivo:"desafio2.py",nome:"converter",tipo:"função",
e:"Função principal do Desafio 2 (algoritmo shunting-yard).",
s:"Converter a notação usual para pós-fixa, resolvendo precedência, associatividade e parênteses.",
f:"Lê os tokens: números vão direto à saída; '(' é empilhado; ')' despeja operadores até achar '('; um operador faz sair da pilha quem deve ser resolvido antes e então é empilhado. No fim, despeja o que sobrou.",
c:"A pilha guarda operadores e parênteses ainda não aplicados. Associativo à esquerda: o topo sai se tiver prioridade maior ou igual (10 - 3 - 2). Para ^: só sai se for estritamente maior (2 ^ 3 ^ 2). '(' funciona como muro e só sai pelo ramo de ')'.",
r:"expressao: string na notação usual.",
p:"Tupla (trace, posfixa, erro). posfixa é uma string como '3 4 2 * +'. Erros: parêntese fechado sem abertura, aberto sem fechamento, caractere inválido.",
u:["d2-tokenizar","d2-const","d2-import","d1-Pilha","d1-empilhar","d1-desempilhar","d1-topo","d1-vazia","d1-visualizar"],ub:["m-processar"],
a:"main.py falha com ImportError ao iniciar. A saída de converter é a entrada de avaliar, então o fluxo inteiro deixa de existir.",
i:"processar e main.py. desafio1.py continuaria íntegro, mas sem receber nada.",
n:[["operadores.topo() != \"(\"","'(' é o muro: nada abaixo dele sai."],["operadores.desempilhar()  # descarta","Remove o '(' sem enviá-lo à saída."],["\"erro: parentese fechado","Pilha esvaziou sem achar '('."],["if token in DIREITA:","Escolhe o critério conforme a associatividade."],["PRIORIDADE[operador_topo] >","Estrito: topo igual fica (^ é à direita)."],["PRIORIDADE[operador_topo] >=","Topo igual sai (esquerda)."],["trace.append((token","Foto do passo; list(saida) é cópia."],["\"erro: parentese aberto","Sobrou '(' sem fechamento."],["(fim)","Última linha do rastreamento."]]},
{id:"m-imports",arquivo:"main.py",nome:"imports",tipo:"imports",
e:"Duas importações.",s:"Trazer os dois desafios para o programa principal.",
f:"De desafio1: fmt, avaliar e tokenizar (com o apelido tokenizar_posfixa). De desafio2: converter.",
c:"O apelido evita confusão com a tokenizar de desafio2, que converter usa internamente e main.py não precisa importar.",
r:"—",p:"Os nomes disponíveis em main.py.",
u:["d1-fmt","d1-avaliar","d1-tokenizar","d2-converter"],ub:["m-processar","m-imp1"],
a:"NameError nas funções que usam os nomes, ou ModuleNotFoundError/ImportError se for um import quebrado. Sem eles o programa não calcula nada.",
i:"processar, imprimir_desafio1 e a cadeia main.py → desafio2.py → desafio1.py."},
{id:"m-texto",arquivo:"main.py",nome:"texto",tipo:"função",
e:"Função auxiliar de impressão.",s:"Transformar listas em texto para o rastreamento.",
f:"Junta os itens com espaço. Lista vazia vira '-', como o enunciado manda.",c:"Só formata; não imprime.",
r:"lista: lista de strings.",p:"Uma string.",
u:[],ub:["m-imp2"],
a:"NameError ao imprimir o rastreamento do Desafio 2 (toda expressão que gera ao menos uma linha de trace). O Desafio 1 não usa texto.",
i:"imprimir_desafio2."},
{id:"m-imp2",arquivo:"main.py",nome:"imprimir_desafio2",tipo:"função",
e:"Função de impressão.",s:"Mostrar o rastreamento da conversão (token | pilha | saida).",
f:"Imprime o cabeçalho e uma linha por item do trace, com token em 5 colunas e pilha em 11.",
c:"Se o trace está vazio (erro antes do primeiro token), não imprime nada. O alinhamento vem de f'{token:<5}'.",
r:"trace: lista de (token, pilha, saida) devolvida por converter.",p:"Nada; só imprime.",
u:["m-texto"],ub:["m-processar"],
a:"NameError em processar logo após converter. O programa não chega nem à avaliação.",
i:"processar."},
{id:"m-imp1",arquivo:"main.py",nome:"imprimir_desafio1",tipo:"função",
e:"Função de impressão.",s:"Mostrar o rastreamento da avaliação (token | pilha).",
f:"Imprime o cabeçalho e uma linha por item do trace, formatando cada número com fmt.",c:"Também ignora trace vazio.",
r:"trace: lista de (token, pilha) devolvida por avaliar.",p:"Nada; só imprime.",
u:["d1-fmt"],ub:["m-processar"],
a:"A conversão ainda funciona e o 'posfixa:' aparece; o NameError só ocorre depois, na etapa de avaliação.",
i:"processar (parte do Desafio 1)."},
{id:"m-processar",arquivo:"main.py",nome:"processar",tipo:"função",
e:"Função que executa o fluxo completo para uma expressão.",s:"Encadear os dois desafios: a saída de converter é a entrada de avaliar.",
f:"Converte e imprime o rastreamento; se houver erro, imprime e volta. Senão imprime a pós-fixa, separa em tokens, avalia, imprime o rastreamento e mostra o resultado ou o erro.",
c:"O 'return' no erro permite seguir para a próxima expressão sem encerrar o programa.",
r:"expressao: string digitada pelo usuário.",p:"Nada; só imprime.",
u:["d2-converter","m-imp2","m-imp1","d1-tokenizar","d1-avaliar","d1-fmt"],ub:["m-main"],
a:"NameError em main ao chamar processar: o programa pede a expressão, mas não faz nada com ela.",
i:"main.",
n:[["trace2, posfixa, erro = converter","Etapa do Desafio 2."],["if erro:","Erro: imprime a mensagem e volta."],["tokens = tokenizar_posfixa","Prepara a entrada do Desafio 1."],["trace1, resultado, erro = avaliar","Etapa do Desafio 1."],["fmt(resultado)","Formata o resultado final."]]},
{id:"m-main",arquivo:"main.py",nome:"main",tipo:"função",
e:"Função de entrada do programa.",s:"Repetir a leitura de expressões até uma linha vazia.",
f:"Lê com input(), sai se a linha for vazia, senão chama processar e imprime uma linha em branco.",
c:"O while True só termina no break.",r:"Nada.",p:"Nada.",
u:["m-processar"],ub:["m-call"],
a:"A chamada final main() daria NameError e o programa terminaria sem fazer nada.",i:"m-call."},
{id:"m-call",arquivo:"main.py",nome:"chamada main()",tipo:"trecho principal",
e:"Última linha do arquivo: inicia o programa.",s:"Executar main ao rodar 'python main.py'.",
f:"Chama main().",c:"Não há 'if __name__ == \"__main__\"': importar main.py em outro arquivo também iniciaria o programa.",
r:"—",p:"—",u:["m-main"],ub:[],
a:"Nada de errado aconteceria, mas o programa não faria nada ao ser executado: as funções seriam só definidas.",i:"O ponto de partida da execução."}
];
